sudo: required
dist: trusty

services:
  - postgresql

addons:
  postgresql: "9.4"
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

cache:
  directories:
    - node_modules

env:
  global:
    - OMNISHARP_URL=https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.9-beta19/omnisharp-ubuntu16-x64-netcoreapp1.0.tar.gz
    - OMNISHARP_ZIP=$TRAVIS_BUILD_DIR/omnisharp-ubuntu-x64-netcoreapp1.0.tar.gz
    - PACKAGE_BASE=build
    - ELECTRON_OUT=$TRAVIS_BUILD_DIR/linq-editor-linux-x64
    - DOTNET_INSTALL_DIR=$TRAVIS_BUILD_DIR/.dotnetcli

before_install:
 - ulimit -n 1024
 - nvm install 6.9
 - echo $DOTNET_INSTALL_DIR
 - wget $OMNISHARP_URL -O $OMNISHARP_ZIP
 # https://github.com/dotnet/core/blob/master/release-notes/preview-download.md
 - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
 - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
 - sudo apt-get update

install:
 - sudo apt-get install dotnet-dev-1.0.0-preview2.1-003155
 - dotnet --info
 - node -v
 - psql -c 'create database world;' -U postgres
 - psql -d world -U postgres -f $TRAVIS_BUILD_DIR/query/sql/world_postgresql.sql
 - chmod -x scripts/build.sh

before_script:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
 - bash ./scripts/build.sh

