sudo: required
dist: trusty

services:
  - postgresql

addons:
  postgresql: "9.4"
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

cache:
  directories:
    - node_modules

env:
  global:
    - CLI_VERSION=latest
    - CLI_ARCH=x64
    - OMNISHARP_URL=https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.9-beta8/omnisharp-ubuntu-x64-netcoreapp1.0.tar.gz
    - OMNISHARP_ZIP=$TRAVIS_BUILD_DIR/omnisharp-ubuntu-x64-netcoreapp1.0.tar.gz
    - DOTNETCLI_URL=https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview1/scripts/obtain/dotnet-install.sh
    - PACKAGE_BASE=build
    - ELECTRON_OUT=$TRAVIS_BUILD_DIR/linq-editor-linux-x64
    - NODE_ENV=PRODUCTION
    - DOTNET_INSTALL_DIR=$TRAVIS_BUILD_DIR/.dotnetcli

before_install:
 - ulimit -n 1024
 - nvm install 6.2
 - echo $DOTNET_INSTALL_DIR
 - wget $OMNISHARP_URL
 - curl -sSL $DOTNETCLI_URL | bash /dev/stdin --version $CLI_VERSION --install-dir $DOTNET_INSTALL_DIR
 - export PATH="$DOTNET_INSTALL_DIR:$PATH"

install:
 - dotnet --info
 - node -v
 - psql -c 'create database testdb;' -U postgres
 - psql -c 'create database testdb2;' -U postgres
 - npm run generate-for-npgsql
 - psql -d testdb -U postgres -f $TRAVIS_BUILD_DIR/testdb-npgsql.sql
 - psql -d testdb2 -U postgres -f $TRAVIS_BUILD_DIR/testdb2-npgsql.sql
 - chmod -x scripts/build.sh

before_script:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
 - bash ./scripts/build.sh
 - npm run int-test-travis
