sudo: required
dist: trusty
services:
  - postgresql
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

env:
  global:
    - CLI_VERSION=latest
    - CLI_ARCH=x64
    - OMNISHARP_URL=https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.9-beta5/omnisharp-ubuntu-x64-netcoreapp1.0.tar.gz
    - OMNISHARP_ZIP=omnisharp-ubuntu-x64-netcoreapp1.0.tar.gz
    - DOTNETCLI_URL=https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview1/scripts/obtain/dotnet-install.sh
    - PACKAGE_BASE=build
    - ELECTRON_OUT=linq-editor-linux-x64
    - NODE_ENV=PRODUCTION
    - DOTNET_INSTALL_DIR=~/.dotnetcli

before_install:
 - ulimit -n 1024
 - nvm install 6.2
 - echo $DOTNET_INSTALL_DIR
 - curl -O $OMNISHARP_URL
 - curl -sSL $DOTNETCLI_URL | bash /dev/stdin --version $CLI_VERSION --install-dir $DOTNET_INSTALL_DIR
 - export PATH="$DOTNET_INSTALL_DIR:$PATH"

install:
 - dotnet --info
 - node -v
 - psql -c 'create database testdb;' -U postgres
 - psql -c 'create database testdb2;' -U postgres
 - npm run generate-for-npgsql
 - psql -d testdb -U postgres -f $TRAVIS_BUILD_DIR/sql-script-testdb.sql
 - psql -d testdb2 -U postgres -f $TRAVIS_BUILD_DIR/sql-script-testdb2.sql
 - chmod -x build_script.sh

script:
 - bash build_script.sh
 - npm run int-test-npgsql
